name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v11
      with:
        name: nix-ros
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix registry add ros github:clearpathrobotics/nix-ros
        nix registry add ros-base github:clearpathrobotics/nix-ros-base
    - run: nix build ros#ci --override-input base ros-base/${GITHUB_SHA}
