name: "Generator"

on:
  pull_request:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v11
      with:
        name: nix-ros
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix registry add ros-base github:clearpathrobotics/nix-ros-base
    - run: nix run ros-base/${GITHUB_SHA}#generate -- --help
