name: "Python Tests"

on:
  pull_request:
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: python3 -m pip install poetry
    - run: poetry install
    - run: poetry run pytest --junitxml=report.xml
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: 'report.xml'
